name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.2'
    - name: フォーマットを実行する
      run: test -z $(gofmt -l .)
    - name: 静的解析を実行する
      run: go vet ./...
    - name: テストを実行する
      run: go test
    - name: ビルドを実行する
      run: go build .
